
const onlineTalkingTips = [
  "Friendly fire is not tolerated.",
  "Use clear and concise language when chatting online.",
  "Respect others' online privacy and boundaries.",
  "Avoid sharing personal information with strangers.",
  "Be cautious when clicking on links from unknown sources.",
  "Use strong and unique passwords for online accounts.",
  "Report and block individuals who engage in harassment or bullying.",
  "Think twice before sharing something you wouldn't say in person.",
  "Be mindful of your tone and the potential for misinterpretation.",
  "Engage in positive and constructive online conversations.",
  "Double-check your messages before sending to avoid typos.",
  "Limit your screen time and take breaks for your well-being.",
  "Use emojis and emoticons to express emotions clearly.",
  "Verify the authenticity of online information before sharing it.",
  "Avoid online arguments; they rarely lead to productive discussions.",
  "Think before posting anything online; it's permanent.",
  "Stay informed about online scams and phishing attempts.",
  "Don't assume everyone online has good intentions.",
  "Remember that online personas may not reflect real-life identities.",
  "Be cautious when sharing photos or videos online.",
  "Respect the rules and guidelines of online communities and forums.",
  "Promote positivity and kindness in online interactions.",
  "Avoid spamming or overloading others with messages.",
  "Engage in discussions you're passionate about and informed on.",
  "Be patient when waiting for responses in online conversations.",
  "Use online communication tools to stay connected with loved ones.",
  "Respect differing opinions and engage in healthy debates.",
  "Set boundaries for your online interactions and stick to them.",
  "Be careful with humor; it can be easily misinterpreted online.",
  "Help others who may be struggling with online issues.",
  "Consider the potential impact of your words on others.",
  "Avoid using excessive caps, as it can be perceived as shouting.",
  "Think before sharing sensitive content; it may harm others.",
  "Remeber, no Russian.",
  "Respect online communities and their shared values.",
  "Use appropriate channels for different types of discussions.",
  "Don't take online disagreements personally.",
  "Seek help if you're experiencing online harassment or cyberbullying.",
  "Remember that not everyone online is who they claim to be.",
  "Protect your personal information from online threats.",
  "Maintain healthy boundaries between your online and offline life.",
  "Practice digital hygiene to keep your devices safe from threats.",
  "Be a responsible digital citizen in all your online activities.",
  "Don't engage in online arguments for the sake of winning.",
  "Keep your online conversations respectful and constructive.",
  "Respect the privacy settings and preferences of others online.",
  "Learn about online privacy settings and use them effectively.",
  "Be mindful of the digital footprint you leave online.",
  "Be skeptical of unsolicited friend requests or connections.",
  "Verify the credibility of sources before sharing news or information.",
  "Teach younger users about online safety and etiquette.",
  "Use secure and trusted platforms for online communication.",
  "Be cautious with what you post on social media; it can be shared widely.",
  "Avoid oversharing personal details online.",
  "Support online campaigns and initiatives that promote positivity.",
  "Show empathy for those who may be facing online harassment.",
  "Respect the copyright and intellectual property of online content.",
  "Use discretion when discussing sensitive or controversial topics online.",
  "Educate yourself on recognizing and dealing with online trolls.",
  "Contribute to creating a safe and inclusive online environment.",
  "Promote and practice good online etiquette and manners.",
  "Remember that the internet is a diverse and global space.",
  "Recognize the impact of cyberbullying on mental health.",
  "Encourage open and respectful discussions in online communities.",
  "Be patient and understanding with less tech-savvy users.",
  "Promote digital well-being and balance in online usage.",
  "Use online platforms to connect with people worldwide.",
  "Be aware of the potential consequences of online actions.",
  "Use secure and private messaging apps when discussing sensitive matters.",
  "Report abusive and harmful content online to the appropriate authorities.",
  "Respect online moderators and administrators.",
  "Be careful with online quizzes and surveys that request personal information.",
  "Know your rights and responsibilities when communicating online.",
  "Advocate for digital literacy and online safety education.",
  "Practice empathy and active listening in online interactions.",
  "Support online initiatives against cyberbullying and online harassment.",
  "Be respectful of different time zones in your online interactions.",
  "Promote online kindness and courtesy in all your messages.",
  "Respect the online rules and policies of websites and platforms.",
  "Promote a culture of digital respect and tolerance.",
  "Understand the potential risks and benefits of online communication.",
  "Be cautious of online relationships with people you've never met in person.",
  "Protect your online accounts with strong and unique passwords.",
  "Use two-factor authentication for added online security.",
  "Learn about online scams and how to avoid falling for them.",
  "Use encryption tools to protect your online conversations.",
  "Promote awareness about online privacy and security.",
  "Encourage healthy online communication and debate.",
  "Lead by example with your online interactions and behavior.",
  "Remember that online conversations have real-life impacts.",
  "Practice empathy and understanding in online conflicts.",
  "Support efforts to combat online hate speech and discrimination.",
  "Use the internet as a tool for education and self-improvement.",
  "Be aware of phishing attempts and online frauds.",
  "Empower others to take control of their online safety and security.",
];

export default onlineTalkingTips;
